### ISSUE TITLE
Create Order Error

### ISSUE THREAD

**Issue by chi07** [paymentwall/module-magento2#7]
When I create new product, add some custom attributes (example: Size L, Size M, size S)
Add to cart this product with custom attribute in admin.
When i checkout => place order => error. can not create order.
Please check

**Comment by miatran** [comment]
Hi shinichi2510,

Thanks for your comment. Could you please send us an email to devsupport@paymentwall.com with some details so we can assist you further:
- your Magento version (2.0 or 2.1)
- the error message, if you can send over a screenshot too it'd be hugely appreciated
- does it happen with normal product (no custom attribute)?

Best,
Paymentwall team
